# Generated by Django 6.0.5 on 2026-05-24 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("industry", models.CharField(blank=True, default="", max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DataImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("SAP", "SAP (Fuel & Procurement)"),
                            ("UTILITY", "Utility (Electricity)"),
                            ("TRAVEL", "Corporate Travel"),
                        ],
                        max_length=16,
                    ),
                ),
                ("file_name", models.CharField(blank=True, default="", max_length=512)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PROCESSING",
                        max_length=16,
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("failed_rows", models.PositiveIntegerField(default=0)),
                ("error_summary", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imports",
                        to="emissions.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmissionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("SAP", "SAP (Fuel & Procurement)"),
                            ("UTILITY", "Utility (Electricity)"),
                            ("TRAVEL", "Corporate Travel"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("SCOPE_1", "Scope 1 — Direct"),
                            ("SCOPE_2", "Scope 2 — Indirect (Energy)"),
                            ("SCOPE_3", "Scope 3 — Value Chain"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        help_text="e.g. Electricity, Flight, Diesel, Hotel",
                        max_length=128,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Sub-category for grouping",
                        max_length=128,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=16)),
                (
                    "unit",
                    models.CharField(
                        help_text="Canonical unit: kWh, liters, km, kg, etc.",
                        max_length=32,
                    ),
                ),
                (
                    "emissions_kg_co2e",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Computed or source-provided CO₂-equivalent in kg",
                        max_digits=16,
                        null=True,
                    ),
                ),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                (
                    "original_payload",
                    models.JSONField(
                        help_text="Verbatim row from the source file/API before normalisation"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("FLAGGED", "Flagged for Review"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("reviewer_notes", models.TextField(blank=True, default="")),
                (
                    "flag_reason",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "data_import",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="emissions.dataimport",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="emissions.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status"],
                        name="emissions_e_tenant__5a7e62_idx",
                    ),
                    models.Index(
                        fields=["source_type"], name="emissions_e_source__067ec8_idx"
                    ),
                    models.Index(fields=["scope"], name="emissions_e_scope_63e497_idx"),
                ],
            },
        ),
    ]
